"""add users table

Revision ID: 70b3c1a2b659
Revises: 85f6f315cb46
Create Date: 2026-08-12 19:09:07.152558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel         # Added to fix FastAPI & Alembic integration inconsistency


# revision identifiers, used by Alembic.
revision: str = '70b3c1a2b659'
down_revision: Union[str, Sequence[str], None] = '85f6f315cb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
